import assert from 'node:assert/strict';
import {getScriptSource} from './extract-script.mjs';
import {createDevice,makeDeck} from './device.mjs';
import {createFakeFirestore} from './fake-firestore.mjs';
const source=getScriptSource(), firestore=createFakeFirestore(), id='aaaaaaaaaaaaaaaa';
const deck=makeDeck([id,'bbbbbbbbbbbbbbbb','cccccccccccccccc']);
const make=(localStorage)=>createDevice({source,firestore,deck,localStorage});
const user={uid:'owner',getToken:async()=> 'test-token'};
const a=make();
a.run(`hideCurrentCard('${id}')`);
assert.equal(a.call('isHidden',id),true);
assert.equal(a.run('answersToday()'),0);
assert.equal(a.snapshotSrs()[id],undefined);
assert.ok(!a.run('session.queue.map(c=>c.id)').includes(id));
const reopened=make(a.localStorage);
assert.equal(reopened.call('isHidden',id),true);
assert.ok(!reopened.run('buildQueue().cards.map(c=>c.id)').includes(id));
a.call('undoHide');assert.equal(a.call('isHidden',id),false);
assert.equal(a.run('session.queue[0].id'),id);
a.call('setCardHidden',id,true);
a.setAuthUser(user);await a.call('syncVisibility');
const b=make();b.setAuthUser(user);await b.call('syncVisibility');
assert.equal(b.call('isHidden',id),true);
b.run('navigator.onLine=false');b.call('setCardHidden',id,false);
assert.equal(b.call('isHidden',id),false);
assert.equal(b.run('visibilityData().pending.length'),1);
b.run('navigator.onLine=true');await b.call('syncVisibility');await a.call('syncVisibility');
assert.equal(a.call('isHidden',id),false);
assert.equal(b.run('visibilityData().pending.length'),0);
const wiped=make();wiped.setAuthUser(user);await wiped.call('syncVisibility');
assert.equal(wiped.call('isHidden',id),false);
a.setAuthUser({uid:'other',getToken:async()=> 'test-token'});
assert.equal(a.call('isHidden',id),false);
console.log('PASS visibility: hide, undo, unchanged schedule/count, reopen, guest adoption, two-device sync, offline restore, wiped-device recovery, account isolation');

const retry=make();retry.setAuthUser(user);retry.run('navigator.onLine=false');retry.call('setCardHidden',id,true);
const realFetch=retry.ctx.fetch;retry.ctx.fetch=async()=>({ok:false,status:503});retry.run('navigator.onLine=true');
await assert.rejects(retry.call('syncVisibility'));
assert.equal(retry.run('visibilityData().pending.length'),1);
assert.equal(retry.call('isHidden',id),true);
retry.ctx.fetch=realFetch;await retry.call('syncVisibility');assert.equal(retry.run('visibilityData().pending.length'),0);
console.log('PASS visibility: failed write retains offline choice and retry drains outbox');
